export const FIRST_SELECT_CHANGE = 'FIRST_SELECT_CHANGE';
export const SECOND_SELECT_CHANGE = 'SECOND_SELECT_CHANGE';
export const INPUT_CHANGE_HANDLER = 'INPUT_CHANGE_HANDLER';
export const SUBMIT_HANDLER = 'SUBMIT_HANDLER';
export const DATA_FETCH = 'DATA_FETCH';
export const TOTAL_ITEMS_FETCH = 'TOTAL_ITEMS_FETCH';
export const PAGINATE = 'PAGINATE';
export const BOOK_FETCH = 'BOOK_FETCH';