export const FIRST_SELECT_CHANGE = 'SELECT_CHANGE';
export const SECOND_SELECT_CHANGE = 'SELECT_CHANGE';
export const INPUT_CHANGE_HANDLER = 'SELECT_CHANGE';
export const SUBMIT_HANDLER = 'SELECT_CHANGE';
export const DATA_FETCH = 'SELECT_CHANGE';
export const PAGINATE = 'SELECT_CHANGE';
